name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ai-study-464204 # GCP 프로젝트 ID
  SERVICE_NAME: gyuwonbot # Cloud Run 서비스 이름
  REGION: us-central1 # Cloud Run 서비스 리전

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Build and Push Docker Image
        run: |
          cd backend
          pwd # 현재 작업 디렉토리 확인
          ls -la # 현재 디렉토리의 파일 목록 확인 (여기에 Dockerfile이 보여야 함)
          gcloud auth configure-docker ${REGION}-docker.pkg.dev
          docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE_NAME}/${SERVICE_NAME}:${{ github.sha }} .
          docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${SERVICE_NAME}/${SERVICE_NAME}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}/${SERVICE_NAME}:${{ github.sha }}
          region: ${{ env.REGION }}
          secrets: |
            DATABASE_URL:/secrets/projects/${{ env.PROJECT_ID }}/secrets/DATABASE_URL
            CALENDAR_ID=/secrets/projects/${{ env.PROJECT_ID }}/secrets/CALENDAR_ID
            DISCORD_WEBHOOK_URL=/secrets/projects/${{ env.PROJECT_ID }}/secrets/DISCORD_WEBHOOK_URL
            GEMINI_API_KEY=/secrets/projects/${{ env.PROJECT_ID }}/secrets/GEMINI_API_KEY
            GOOGLE_SERVICE_ACCOUNT_JSON=/secrets/projects/${{ env.PROJECT_ID }}/secrets/GOOGLE_SERVICE_ACCOUNT_JSON
            